pub mod compat;
pub mod details;
pub mod error;
pub mod geometry;
pub mod ids;
pub mod index;
pub mod install;
pub mod listing;
pub mod manifest;
pub mod operation;
pub mod pane;
pub mod registry;
pub mod search;
pub mod sidebar_decision;
pub mod source;
pub mod text;
pub mod uninstall;
pub mod version;

pub const PLUGIN_ID: &str = "herdr-marketplace";
pub const SIDEBAR_ENTRYPOINT: &str = "sidebar";
pub const SIDEBAR_TOKEN_KEY: &str = "herdr_marketplace_sidebar";
pub const DETAILS_ENTRYPOINT: &str = "details";
pub const DETAILS_TOKEN_KEY: &str = "herdr_marketplace_details";
/// JSON `DetailsTarget` handed to a details pane.
pub const DETAILS_ENV: &str = "HERDR_MARKETPLACE_DETAILS";
pub const TOKEN_VALUE: &str = "v1";
pub const EXPLORER_TOKEN_KEY: &str = "herdr-sidebar-explorer";
pub const PREFERRED_OUTER_COLUMNS: u16 = 32;
pub const MIN_SIDEBAR_SHARE: f64 = 0.15;
pub const MAX_SIDEBAR_SHARE: f64 = 0.50;
pub const DEFAULT_INDEX_URL: &str = "https://assets.herdr.dev/plugins/index.json";
pub const INDEX_URL_ENV: &str = "HERDR_MARKETPLACE_INDEX_URL";
